using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.1.2925.42952")]
[assembly: AssemblyFileVersionAttribute("1.1.2925.42952")]
[assembly: AssemblyCopyrightAttribute("Copyright theJoyOfCode.com 2012")]
[assembly: AssemblyProductAttribute("ClassTester")]
[assembly: AssemblyCompanyAttribute("theJoyOfCode.com")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("1.1.2925.42952")]

